new YAML file

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -15,7 +15,7 @@ jobs:
 
     # The type of machine that will run this job
     # GitHub provides a temporary Ubuntu Linux machine
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     # A job consists of multiple steps
     steps:
@@ -32,7 +32,7 @@ jobs:
         with:
           python-version: "3.9"
 
-      # Step 3: Install project dependencies
+      # Step 3: Install project dependencies (for pytest)
       # pip is upgraded first, then packages from requirements.txt are installed
       - name: Install dependencies
         run: |
@@ -45,6 +45,23 @@ jobs:
         run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
       - name: Run tests
         run: pytest -q
+
+      # Step 5: Pull the pre-built Docker image from Docker Hub (public image)
+      - name: Pull Docker image
+        run: docker pull amfarahani/iris2026:v1
+
+      # Step 6: Run the container (background) and expose its port
+      # NOTE: This runs on the GitHub runner, not your laptop
+      - name: Run container
+        run: |
+          docker rm -f iris-api || true
+          docker run -d --name iris-api -p 8080:8080 amfarahani/iris2026:v1
+
+
+      # Step 8: Cleanup (stop and remove container so the runner is clean)
+      - name: Cleanup
+        if: always()
+        run: docker rm -f iris-api || true
     
 
 
